### ISSUE TITLE
Unable to read hashdata.xml (slave-side)

### ISSUE THREAD

**Issue by 24mu13** [RogueScholar/service.addonsync#3]
I installed the addon as **master**: everything fine. My configuration files are correctly (apparently) saved on the NFS path I defined.

But, **slave** side, when I manually syncronise, I get the following error:
```
2020-05-17 18:58:32.836 T:1368388480   ERROR: service.addonsync: AddonData: Failed to read in file nfs://192.168.2.10/volume1/software/kodi_addons_settings/hashdata.xml
2020-05-17 18:58:32.861 T:1368388480   ERROR: service.addonsync: AddonData: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.addonsync/resources/lib/core.py", line 282, in _loadHashRecord
                                                hashRecord = ET.ElementTree(ET.fromstring(recordFileStr))
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
                                            ParseError: junk after document element: line 2, column 381
```

Any idea?

**Comment by 24mu13** [comment]
In my case the original had an extra "c>" at the end.

```
<?xml version='1.0' encoding='UTF-8'?>
<addonsync><addon name="xx" version="xx">xx</addon></addonsync>c>
```
